config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :users, except: [:index, :destroy, :show, :edit, :update]
  resource :user, only: [:show, :destroy, :edit, :update]
  get "/login", to: "users#login"
  post "/login", to: "users#login_action"
  delete "/login", to: "users#logout"

  resources :works
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, length: {minimum: 4}
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user_by_session, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_clean)
      redirect_to root_path, notice: "成功修改帳號密碼"
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_clean) # 請查看 strong parameters 概念
    if @user.save
      session[:login_token] = @user.email
      redirect_to root_path, notice: "已成功註冊！"
    else
      render :new
    end
  end

  def logout
    session[:login_token] = nil
    redirect_to root_path, notice: "已成功登出！"
  end

  def login
    @user = User.new
  end

  def login_action
    find_user

    if @user
      session[:login_token] = @user.email
      redirect_to root_path, notice: "歡迎 #{@user.email} 您以成功登入！"
    else
      render :login
      flash[:notice] = "帳號或密碼錯誤！"
    end
  end

  def destroy
    @user.destroy
    session[:login_token] = nil
    redirect_to root_path, notice: "已註銷帳號"
  end
  
  private
  def find_user
    @user = User.find_by(email: params[:user][:email])
  end

  def find_user_by_session
    @user = User.find_by(email: session[:login_token])
  end

  def user_clean
    params.require(:user).permit(:email, :password, :tel, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  def index
    @works = Work.all
  end

  def show
  end

  def new
    @work = Work.new
  end

  def edit
  end

  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to works_path, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to works_path, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_path, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_work
      @work = Work.find(params[:id])
    end

    def work_params
      params.require(:work).permit(:title, :name, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  private
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice%>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<h1>footer</h1>

app/views/shared/_navbar.html.erb
<!doctype html>
<html lang="en">

<head>

  <title>Hello, world!</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
      <img src="https://picsum.photos/40/40/?random=1">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">首頁<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">最新消息</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            關於密式
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">密式簡介</a>
            <a class="dropdown-item" href="#">關於密式</a>
            <a class="dropdown-item" href="#">園區地圖</a>
            <a class="dropdown-item" href="#">園內規約</a>
            <a class="dropdown-item" href="#">密式特色</a>
            <a class="dropdown-item" href="#">代訂合菜</a>
            <a class="dropdown-item" href="#">交通資訊</a>
            <a class="dropdown-item" href="#">鄰近景點</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            房型展示
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">依山之屋</a>
            <a class="dropdown-item" href="#">觀山之屋</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">密式之眼</a>
            <a class="dropdown-item" href="#">密式之頂</a>
            <a class="dropdown-item" href="#">映月之屋</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">櫻花之盡</a>
            <a class="dropdown-item" href="#">沒日之嶺</a>
            <a class="dropdown-item" href="#">密式雨棚</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            密式柑仔店
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">密式桌遊</a>
            <a class="dropdown-item" href="#">裝備租借</a>
            <a class="dropdown-item" href="#">販賣物品</a>
            <a class="dropdown-item" href="#">咖啡廳菜單</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">聯絡密式</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">線上訂房</a>
        </li>
        <li class="nav-item active">
          <%= link_to "玩具/作業區", works_path, class: 'nav-link'%>
        </li>
      </ul>
      <% if session[:login_token]%>
        <div class="nav-link">
        <%= link_to "您好 #{session[:login_token]}", url_for(action: 'show', controller: 'users')%>
        </div>
        <%= link_to "登出", login_path, method:'delete',class:'nav-link' %>
      <% else %>
        <%= link_to "註冊", new_user_path, class:'nav-link' %>
        <%= link_to "登入", login_path, class:'nav-link'%>
      <% end %>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</body>

</html>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form|%>
  <% if user.errors.any?%>
    <ul>
      <% user.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
      <% end %>
    </ul>
  <% end %>
<div>
  <%= form.label :email%>
  <%= form.text_field :email %>
</div>
<div>
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>
<div>
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
</div>
<div>
  <%= form.label :tel %>
  <%= form.text_field :tel %>
</div>
<div>
  <%= form.submit "送出"%>
</div>
<% end%>

app/views/users/edit.html.erb
<h1>修改使用者資料</h1>

<%= render 'form', user: @user %>

app/views/users/login.html.erb
<h1>使用者登入</h1>

<%= form_with model:@user, url:"/login", local: true do |form| %>
  <div>
    <%= form.label :email, "帳號"%>
    <%= form.text_field :email %>
  </div>
    <div>
    <%= form.label :password, "密碼"%>
    <%= form.password_field :password %>
  </div>
  <%= form.submit "登入"%>
<% end %>

app/views/users/new.html.erb
<h1>使用者註冊</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1>
  帳號：<%= @user.email %>
</h1>
<h1>
  電話：<%= @user.tel %>
</h1>
<div>
  <%= link_to "註銷使用者", url_for('user'), method: 'delete', data: {confirm: "是否確認刪除?"}%>
</div>
<div>
  <%= link_to "修改使用者資料", edit_user_path %>
</div>

app/views/welcome/index.html.erb
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <title>Hello, world!</title>
</head>

<body>


  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://picsum.photos/1500/400/?random=2" class="d-block w-100">
      </div>
      <div class="carousel-item">
        <img src="https://picsum.photos/1500/400/?random=3" class="d-block w-100">
      </div>
      <div class="carousel-item">
        <img src="https://picsum.photos/1500/400/?random=4" class="d-block w-100">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>



  <div class="container">
    <div class="row">
      <div class="col-12 col-md-3">
        <ul class="list-group list-group-flush">選單列表
          <li class="list-group-item">Cras justo odio</li>
          <li class="list-group-item">Dapibus ac facilisis in</li>
          <li class="list-group-item">Morbi leo risus</li>
          <li class="list-group-item">Porta ac consectetur ac</li>
          <li class="list-group-item">Vestibulum at eros</li>
        </ul>
      </div>
      <div class="col-12 col-md-9"></div>
    </div>
  </div>




  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>

</html>

app/views/works/_form.html.erb
<%= form_with(model: work, local: true) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
        <% work.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.title %></td>
        <td><%= work.name %></td>
        <td><%= work.desc %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>一個新的作業或玩具</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @work.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @work.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @work.desc %>
</p>

<% if @work.name == "一個圖片"%>
<div class="text-center">
  <h1 class="m-3">一個圖片</h1>
  <input type="text" id="input" class="img-link w-50" />
  <div class="m-5">
    <button type="button" class="btn btn-primary">
      送出
    </button>
  </div>
  <div id="img-container" class="m-5 row">
    
  </div>
</div>
<% end %>

<%= link_to 'Edit', edit_work_path(@work) %> | 
<%= link_to 'Back', works_path %>